// AQUI FICARAO AS CORES DO APLICATIVO. CADA COR É COMO ATRIBUTO DE UMA CLASSE
import 'package:flutter/cupertino.dart';

class MainColors {
  // ESSE É UM EXEMPLO DE COMO SERÁ A COR PRIMÁRIA DO TEMA CLARO
  // O FLUTTER TRABALHA COM CORES NESSE PADRÃO: "0xFF" E EM SEGUIDA O CÓDIGO DA COR
  static const PRIMARY_COLOR_LIGHT = Color(0xFF10B645);

  // AQUI É UM EXEMPLO DA COR PRIMÁRIA PARA O APP NO MODO ESCURO
  static const PRIMARY_COLOR_DARK = Color(0xFF1B7135);
}
