// SALVE OS AUDIOS COMO CONSTANTES PARA PODER SER USADO NO APPLICATIVO
// ESSE É UM EXEMPLO DE COMO DEVE SER FEITO: NOME_DO_ARQUIVO COM FINAL "_AUDIO";
// O CAMINHO DO ARQUIVO DEVE SER FEITO DA PASTA RAIZ: lib/ui/assets/etc;
const HELLO_WORLD_AUDIO = "lib/ui/assets/audios/hello_world.mp3";
