// SALVE AS IMAGES COMO CONSTANTES PARA PODER SER USADO NO APPLICATIVO
// ESSE É UM EXEMPLO DE COMO DEVE SER FEITO: NOME_DO_ARQUIVO COM FINAL "_IMAGE";
// O CAMINHO DO ARQUIVO DEVE SER FEITO DA PASTA RAIZ: lib/ui/assets/etc;
const HELLO_WORLD_IMAGE = "lib/ui/assets/audios/hello_world.png";